# Deployment
## Create a Deployment named nginx with 3 replicas. The Pods should use the nginx:1.23.0 image and the name nginx. The Deployment uses the label tier=backend. The Pod template should use the label app=v1.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: v1
  template:
    metadata:
      labels:
        app: v1
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.0
        ports:
        - containerPort: 80

## Assign the change cause "Pick up patch version" to the revision.
### kubectl annotate deployment nginx-deployment kubernetes.io/change-cause="Pick up patch version" --overwrite

## Scale the Deployment to 5 replicas.
### kubectl scale --replicas=5 deployment nginx-deployment


