# init container
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
  - name: myapp-init
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 20']

# multi container
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: myapp-init
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 20']